import type { CategoryConfig, RecordItem } from "../types/app";

export const categories: CategoryConfig[] = [
  {
    key: "dashboard",
    name: "Dashboard",
    icon: "bi-speedometer2",
    description: "",
    fields: [],
  },
  {
    key: "bulanIni",
    name: "Jadwal Reguler",
    icon: "bi-calendar-week",
    description: "",
    fields: [
      { key: "cabang", label: "Cabang", placeholder: "Semarang 1" },
      { key: "kelas", label: "Kelas", placeholder: "PIKPU-1" },
      { key: "tanggal", label: "Tanggal", type: "date" },
      { key: "mapel", label: "Mata Pelajaran", placeholder: "Matematika" },
      { key: "pengajar", label: "Pengajar", placeholder: "Pak Dimas" },
      { key: "waktu", label: "Waktu", placeholder: "08:00 - 09:30" },
      { key: "catatan", label: "Catatan", placeholder: "Ujian Bab 2" },
    ],
  },
  {
    key: "jadwalTambahanPelayanan",
    name: "Jadwal Tambahan & Pelayanan",
    icon: "bi-calendar-plus",
    description: "",
    fields: [
      { key: "cabang", label: "Cabang", placeholder: "Semarang 1" },
      { key: "kelas", label: "Kelas", placeholder: "PIKPU-1" },
      { key: "tanggal", label: "Tanggal", type: "date" },
      { key: "mapel", label: "Mata Pelajaran", placeholder: "Matematika" },
      { key: "pengajar", label: "Pengajar", placeholder: "Pak Dimas" },
      { key: "waktu", label: "Waktu", placeholder: "08:00 - 09:30" },
      { key: "catatan", label: "Catatan", placeholder: "Ujian Bab 2" },
    ],
  },
  {
    key: "hapusJadwal",
    name: "Hapus Jadwal",
    icon: "bi-trash3",
    description: "",
    fields: [],
  },
  {
    key: "printJadwal",
    name: "Print Jadwal",
    icon: "bi-printer",
    description: "",
    fields: [],
  },
  {
    key: "monitoringKelas",
    name: "Monitoring Kelas",
    icon: "bi-clipboard-data",
    description: "",
    fields: [],
  },
  {
    key: "suratTugasMengajar",
    name: "Surat Tugas Mengajar",
    icon: "bi-file-earmark-text",
    description: "",
    fields: [],
  },
  {
    key: "liburNasional",
    name: "Libur Nasional",
    icon: "bi-flag",
    description: "Kelola tanggal libur nasional",
    fields: [],
  },
  {
    key: "mataPelajaran",
    name: "Mata Pelajaran",
    icon: "bi-journal-text",
    description: "",
    fields: [],
  },
  {
    key: "pengajar",
    name: "Pengajar",
    icon: "bi-person-badge",
    description: "",
    fields: [],
  },
  {
    key: "penempatanPengajar",
    name: "Penempatan Pengajar",
    icon: "bi-diagram-3",
    description: "",
    fields: [],
  },
  {
    key: "izinPengajar",
    name: "Izin Pengajar",
    icon: "bi-calendar-x",
    description: "",
    fields: [],
  },
  {
    key: "permintaanPengajarAntarCabang",
    name: "Permintaan Pengajar Antar Cabang",
    icon: "bi-arrow-left-right",
    description: "",
    fields: [],
  },
  {
    key: "accounts_cabang",
    name: "accounts_cabang",
    icon: "bi-people",
    description: "Kelola akun cabang untuk login.",
    fields: [],
  },
  {
    key: "donasi",
    name: "Kelola Donasi",
    icon: "bi-heart-fill",
    description: "Kelola data rekening dan donasi pemeliharaan database.",
    fields: [],
  },
  {
    key: "settings",
    name: "Pengaturan",
    icon: "bi-gear-wide-connected",
    description: "Pengaturan aplikasi dan maintenance cache.",
    fields: [],
  },
];

export const initialRecords: Record<string, RecordItem[]> = {
  bulanIni: [],
};